# Find EGL
#
# EGL_INCLUDE_DIR
# EGL_LIBRARY
# EGL_FOUND

FIND_PATH(EGL_INCLUDE_DIR NAMES EGL/egl.h)

SET(EGL_NAMES ${EGL_NAMES} egl EGL)
FIND_LIBRARY(EGL_LIBRARY NAMES ${EGL_NAMES})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(EGL DEFAULT_MSG EGL_LIBRARY EGL_INCLUDE_DIR)

MARK_AS_ADVANCED(EGL_INCLUDE_DIR EGL_LIBRARY)
